---

- name: Set the Github API endpoint
  set_fact:
    _nginx_exporter_github_api_url: |-
      {% if nginx_exporter_release_tag == 'latest' %}
      https://api.github.com/repos/nginxinc/nginx-prometheus-exporter/releases/latest
      {% else %}
      https://api.github.com/repos/nginxinc/nginx-prometheus-exporter/releases/tags/{{ nginx_exporter_release_tag }}
      {% endif %}

- name: Set the Github API token
  set_fact:
    _nginx_exporter_github_api_token: "{{ lookup('env', 'GITHUB_API_TOKEN') }}"

- name: Fetch the nginx-exporter release information from Github
  uri:
    url: "{{ _nginx_exporter_github_api_url }}"
    method: GET
    headers:
      Authorization: "{% if _nginx_exporter_github_api_token %}token {{ _nginx_exporter_github_api_token }}{% endif %}"
  check_mode: no
  register: _nginx_exporter_github_release
  until: |
    'status' in _nginx_exporter_github_release
      and _nginx_exporter_github_release['status'] == 200
  retries: 5
  delay: 15

- name: Get the tag of the latest nginx-exporter Github release
  set_fact:
    nginx_exporter_release_tag: "{{ _nginx_exporter_github_release['json'] | json_query('tag_name') }}"
  when: nginx_exporter_release_tag == "latest"

#- debug:
#    msg: "Json {{ _nginx_exporter_github_release['json'] }}"
#
#- debug:
#    msg: "Tag {{ nginx_exporter_release_tag }}"

- name: Set the Github download URL for the nginx-exporter release
  set_fact:
    nginx_exporter_release_url: "{{ _nginx_exporter_github_release['json'] | json_query(_nginx_exporter_release_asset_url_query) }}"
  vars:
    _nginx_exporter_release_asset_url_query: "assets[?name=='{{ hostvars[inventory_hostname] | nginx_exporter_release_build(nginx_exporter_release_tag) }}.tar.gz'] | [0].browser_download_url"  # noqa 204

#- debug:
#    msg: "URL {{ nginx_exporter_release_url }}"
